# Generated by Django 2.2.9 on 2020-01-09 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableChap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stt', models.PositiveSmallIntegerField(default=0)),
                ('chapSo', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('chapComic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
        migrations.CreateModel(
            name='ViewComic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('anhChap', models.ImageField(upload_to='chap_image')),
                ('viewChap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.TableChap')),
            ],
        ),
        migrations.CreateModel(
            name='DetailComic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatar_comic')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
    ]
